##########################
#
# configuration file for pipeline_singlecell
#
##########################

# primary assembly downloaded according to documentation instructions
# wget http://ftp.ensembl.org/pub/release-105/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
genome_file: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

# Provide a reference geneset (suffix= ".gtf.gz")
# Geneset should be located in working directory
# wget http://ftp.ensembl.org/pub/release-105/gtf/homo_sapiens/Homo_sapiens.GRCh38.105.gtf.gz
geneset: Homo_sapiens.GRCh38.99.gtf.gz


# Specify if there is a mixed species input (i.e. mouse and human)
mixed_species: 0

# Location of the data. 0 for the current directory
data: data.dir



#######################
# Kallisto
#######################

kallisto:
  # kmer size for kallisto. Default is 31 and max is 31
  # Used to generate the kallisto index
  # Kallisto will ignore transcripts shorter than this
  kmer: 31

  # Number of threads for kallisto
  threads: 5

  # Whether to generate a BUStools file
  bustools: 0
  # Must specify a single cell tchnology to generate bustools file
  # allowable technology:
  # 10Xv1
  # 10Xv2
  # DropSeq
  # inDrop
  # CELSeq
  # CELSeq2
  # SCRBSeq
  # Not that 10Xv3 is not supported in version 0.44 of kallisto
  sctechnology: 10Xv3

  # whether to output as loom or h5
  # Must specify:
  # loom
  # h5ad
  output_format: loom

  # Which workflow to use:
  # options include: standard,lamanno,nucleus,kite,kite:10xFB
  # Type of workflow. Use `lamanno` for RNA velocity based
  #                      on La Manno et al. 2018 logic. Use `nucleus` for RNA
  #                      velocity on single-nucleus RNA-seq reads. Use `kite`
  #                      for feature barcoding. Use `kite:10xFB` for 10x
  #                      Genomics Feature Barcoding technology. (default:
  #                      standard)
  workflow: nucleus

  # If you specify a custom barcode in the kallisto_technology then you
  # need to specify a custom whitelist

  whitelist:


