---
title: "Integrate data"
output: 
  html_document:
    code_folding: hide
---

The aim of this Rmardown document is to integrate all of the samples together in one seurat object. This Rmarkdown page will only render if there are more than 2 samples in the analysis.

# Import the Seurat objects
```{r}
library(Seurat)
library(scClassify)
library(annotables)
library(harmony)
# Import single cell experiment class object from 
samples <- str_replace(Sys.glob("../kallisto.dir/*"), "../kallisto.dir/", "")

# Stop if only one file
if (length(samples) == 1){
  knitr::knit_exit()
}

sce <- readRDS("integrated_CCA.rds")
```

# Run harmony

```{r}
options(repr.plot.height = 2.5, repr.plot.width = 6)
sce <- SCTransform(sce, verbose = FALSE)
sce <- RunHarmony(sce, "orig.ident", plot_convergence = TRUE, assay.use="SCT")
```

# Run Dim plot to see embeddings

```{r}
harmony_embeddings <- Embeddings(sce, 'harmony')
DimPlot(object = sce, reduction = "harmony", pt.size = .1, group.by = "orig.ident")
```

# 

```{r}
VlnPlot(object = sce, features = "harmony_1", group.by = "orig.ident", pt.size = .1)
```

# Downstream analysis

```{r}
sce <- sce %>% 
    RunUMAP(reduction = "harmony", dims = 1:30) %>% 
    FindNeighbors(reduction = "harmony", dims = 1:30) %>% 
    FindClusters(resolution = 0.5) %>% 
    identity()
```


# UMAP embeddings with harmony

```{r}
options(repr.plot.height = 4, repr.plot.width = 10)
DimPlot(sce, reduction = "umap", group.by = "orig.ident", pt.size = .1, split.by = 'orig.ident')
```

```{r}
options(repr.plot.height = 4, repr.plot.width = 6)
DimPlot(sce, reduction = "umap", label = TRUE, pt.size = .1)
```
