---
title: "3d plot"
output: html_document
---

This is optional for the workshop but I found the code within this repo very interesting: https://github.com/Dragonmasterx87/Interactive-3D-Plotting-in-Seurat-3.0.0. The code allows you to make 3D rendered plots for visualisation.

```{r}
#Install packages and dependencies
#install.packages('scatterplot3d')
#install.packages('rgl')
#install.packages('rmarkdown')
#install.packages('magick')

# Load packages
library(magick)
library(rmarkdown)
library(rgl) #interactive 3d plotting
library(Seurat)
```

# Make TSNE 

Run a TSNE to 3 embeddings

```{r}
yourseuratobject <- readRDS("seurat_object.rds")

yourseuratobject <- RunTSNE(yourseuratobject,
                        reduction.use = "pca",
                        dims.use = 1:10,
                        dim.embed = 3)

tsne_1 <- yourseuratobject[["tsne"]]@cell.embeddings[,1]
tsne_2 <- yourseuratobject[["tsne"]]@cell.embeddings[,2]
tsne_3 <- yourseuratobject[["tsne"]]@cell.embeddings[,3]

#yourseuratobject <- RunUMAP(yourseuratobject,
#        reduction = "pca", dims = 1:10, n.components = 3)

```

# TSNE plot

```{r}
TSNEPlot(yourseuratobject, label = FALSE, 
         cols = c("lightseagreen",
                  "gray50",
                  "darkgreen",
                  "red4",
                  "red",
                  "turquoise4",
                  "black",
                  "yellow4",
                  "royalblue1",
                  "lightcyan3",
                  "peachpuff3",
                  "khaki3",
                  "gray20",
                  "orange2",
                  "royalblue4",
                  "yellow3",
                  "gray80",
                  "darkorchid1",
                  "lawngreen",
                  "plum2",
                  "darkmagenta"),
         pt.size = 2)

```

# Feature plot

```{r}
FeaturePlot(object = yourseuratobject, features = c("PECAM1"), min.cutoff =0, max.cutoff = 1, label = FALSE, 
            cols = c("grey", "red"), pt.size = 2)
```

# 3D plotting

```{r}
plot3d(x = tsne_1, y = tsne_2, z = tsne_3,
       col = c("lightseagreen",
               "gray50",
               "darkgreen",
               "red4",
               "red",
               "turquoise4",
               "black",
               "yellow4",
               "royalblue1",
               "lightcyan3",
               "peachpuff3",
               "khaki3",
               "gray20",
               "orange2",
               "royalblue4",
               "yellow3",
               "gray80",
               "darkorchid1",
               "lawngreen",
               "plum2",
               "darkmagenta")[yourseuratobject@active.ident],
       type = "s", 
       size = 0.5, 
       box = FALSE)

rgl::rglwidget() #save as html
```
