##########################
#
# configuration file for pipeline_singlecell
#
##########################


# Number of features to keep as a minimum - we suggest a minimum of 300
features_greater: 300

# Maximum number of features to filter- we suggest 6000 to begin with
features_less: 6000

# mitochondrial ratio less than value to keep
mito: 0.1

# number of UMIs to filter outless than
umis: 500

# Number of genes less than to filter out
genes: 300