name: scflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Debug File Structure
        run: ls -R

      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: ${{ env.installer-url }}
          python-version: ${{ matrix.python-version }}
          channels: conda-forge, bioconda, defaults
          channel-priority: true

      - name: Create and Activate Environment
        run: |
          micromamba create --name scflow --file conda/environments/scflow.yml
          micromamba activate scflow
          python --version

      - name: Install Additional Dependencies
        run: |
          micromamba run -n scflow pip install pep8

      - name: Lint and Test
        run: |
          micromamba run -n scflow python setup.py install
          micromamba run -n scflow pycodestyle --ignore=E501 tests
          micromamba run -n scflow nosetests -v tests/test_import.py
          micromamba run -n scflow nosetests -v tests/test_style.py
          micromamba run -n scflow nosetests -v tests/test_pipeline_control.py
