name: scflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"  # Install Miniforge
          python-version: ${{ matrix.python-version }}
          channels: conda-forge, bioconda, defaults
          channel-priority: true

      - name: Install mamba
        run: |
          conda install -n base -c conda-forge mamba
          mamba --version

      - name: Debug File Structure
        run: ls -R

      - name: Create and Activate Environment with mamba
        run: |
          mamba env create --name scflow --file conda/environments/scflow.yml
          source activate scflow
          python --version

      - name: Install Additional Dependencies
        run: |
          source activate scflow
          pip install pep8

      - name: Lint and Test
        run: |
          source activate scflow
          python setup.py install
          pycodestyle --ignore=E501 tests
          nosetests -v tests/test_import.py
          nosetests -v tests/test_style.py
          nosetests -v tests/test_pipeline_control.py
