name: scflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          python-version: ${{ matrix.python-version }}
          channels: conda-forge, bioconda, defaults
          channel-priority: true

      - name: Create Environment
        run: |
          conda env create --file conda/environments/testing.yml
          conda list

      - name: Activate Environment and Install Additional Dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            source /usr/share/miniconda3/etc/profile.d/conda.sh
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            source /Users/runner/miniconda3/etc/profile.d/conda.sh
          fi
          conda activate scflow
          pip install pep8 pycodestyle

      - name: Lint and Test
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            source /usr/share/miniconda3/etc/profile.d/conda.sh
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            source /Users/runner/miniconda3/etc/profile.d/conda.sh
          fi
          conda activate scflow
          pip install .
          pycodestyle --ignore=E501 tests
          nosetests -v tests/test_import.py
          nosetests -v tests/test_style.py
          nosetests -v tests/test_pipeline_control.py
