name: scflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"  # Install the latest version of Miniforge
          python-version: ${{ matrix.python-version }}
          channels: conda-forge, bioconda, defaults
          channel-priority: true

      - name: Create and Activate Environment
        run: |
          conda env create  --file conda/environments/testing.yml
          conda init
          conda activate scflow
          conda list

      - name: Install Additional Dependencies
        run: |
          conda activate scflow
          pip install pep8

      - name: Lint and Test
        run: |
          conda activate scflow
          pip install .
          pycodestyle --ignore=E501 tests
          nosetests -v tests/test_import.py
          nosetests -v tests/test_style.py
          nosetests -v tests/test_pipeline_control.py
