name: scflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: ${{ env.installer-url }}
          python-version: ${{ matrix.python-version }}
          channels: conda-forge, bioconda, defaults
          channel-priority: true
          activate-environment: cgat-core
          environment-file: conda/environments/testing.yml

      - name: Configure Conda Paths
        run: echo "/usr/share/miniconda3/condabin" >> $GITHUB_PATH

      - name: Show conda
        run: |
          conda info
          conda list

      - name: Debug File Structure
        run: ls -R

      - name: Install Additional Dependencies
        run: |
          pip install pep8

      - name: Lint and Test
        run: |
          source activate scflow
          python setup.py install
          pycodestyle --ignore=E501 tests
          nosetests -v tests/test_import.py
          nosetests -v tests/test_style.py
          nosetests -v tests/test_pipeline_control.py
